# Generated by Django 5.0 on 2024-02-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_Servicio', models.BigAutoField(primary_key=True, serialize=False)),
                ('Servicio', models.CharField(max_length=100)),
            ],
        ),
    ]
