# Generated by Django 5.0 on 2024-04-02 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_Servicio', models.BigAutoField(primary_key=True, serialize=False)),
                ('Servicio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id_Registro', models.BigAutoField(primary_key=True, serialize=False)),
                ('Alumno', models.CharField(max_length=500)),
                ('Matricula', models.CharField(max_length=6)),
                ('Sexo', models.CharField(max_length=1)),
                ('Carrera', models.CharField(max_length=500)),
                ('Correo', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=10)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('Servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecepcionCOBE.servicio')),
            ],
        ),
    ]
