# Generated by Django 5.0 on 2024-02-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecepcionCOBE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id_Registro', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Alumno', models.CharField(max_length=500)),
                ('Sexo', models.CharField(max_length=1)),
                ('Carrera', models.CharField(max_length=500)),
                ('Telefono', models.CharField(max_length=10)),
                ('Servicio', models.CharField(max_length=1)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
