# Generated by Django 5.0 on 2024-02-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecepcionCOBE', '0003_alter_registrodiario_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodiario',
            name='Correo',
            field=models.CharField(default='al201316@alumnos.uacj.mx', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='Matricula',
            field=models.CharField(default='123456', max_length=6),
            preserve_default=False,
        ),
    ]
