# Generated by Django 5.0 on 2024-02-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecepcionCOBE', '0004_registrodiario_correo_registrodiario_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodiario',
            name='id_Registro',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
