# Generated by Django 5.0 on 2024-01-19 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsesoriaAcademica',
            fields=[
                ('id_Asesoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('Matricula', models.CharField(max_length=6)),
                ('Nombre_Alumno', models.CharField(max_length=500)),
                ('Telefono', models.CharField(max_length=10)),
                ('Correo', models.CharField(max_length=24)),
                ('Semestre', models.CharField(max_length=2)),
                ('NumMaterias', models.CharField(max_length=2)),
                ('Carrera', models.CharField(max_length=500)),
                ('Materia', models.CharField(max_length=100)),
                ('Reprobadas', models.CharField(max_length=2)),
                ('Tema', models.TextField()),
                ('Horario', models.TextField()),
                ('Comentario', models.TextField()),
                ('Asesor', models.CharField(max_length=500)),
                ('Estatus', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaAcademico',
            fields=[
                ('id_Carrera', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_Materia', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Carrera', models.ManyToManyField(to='Informacion_Academica.programaacademico')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('Matricula', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Nombre_Alumno', models.CharField(max_length=500)),
                ('Nacionalidad', models.CharField(max_length=15)),
                ('Sexo', models.CharField(max_length=1)),
                ('Carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacion_Academica.programaacademico')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id_Tema', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nombre', models.TextField()),
                ('Materias', models.ManyToManyField(to='Informacion_Academica.materia')),
            ],
        ),
    ]
