# Generated by Django 5.0 on 2024-04-02 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('Matricula', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Nombre_Alumno', models.CharField(max_length=500)),
                ('Nacionalidad', models.CharField(max_length=15)),
                ('Sexo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='AsesorAcademico',
            fields=[
                ('id_Asesor', models.BigAutoField(primary_key=True, serialize=False)),
                ('Materias', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EstatusAsesoria',
            fields=[
                ('id_Estatus', models.BigAutoField(primary_key=True, serialize=False)),
                ('Estatus', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaAcademico',
            fields=[
                ('id_Carrera', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id_Rango', models.BigAutoField(primary_key=True, serialize=False)),
                ('Rango', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Insidencia',
            fields=[
                ('id_insidencia', models.BigAutoField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='AsesoriaPsicologica',
            fields=[
                ('id_Asesoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('Matricula', models.CharField(max_length=6)),
                ('Telefono', models.CharField(max_length=10)),
                ('Asistencia', models.BooleanField(default=False)),
                ('Asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacion_Academica.asesoracademico')),
            ],
        ),
        migrations.CreateModel(
            name='AsesoriaAcademica',
            fields=[
                ('id_Asesoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('Matricula', models.CharField(max_length=6)),
                ('Nombre_Alumno', models.CharField(max_length=500)),
                ('Telefono', models.CharField(max_length=10)),
                ('Correo', models.CharField(max_length=24)),
                ('Semestre', models.CharField(max_length=2)),
                ('NumMaterias', models.CharField(max_length=2)),
                ('Carrera', models.CharField(max_length=500)),
                ('Materia', models.CharField(max_length=100)),
                ('Reprobadas', models.CharField(max_length=2)),
                ('Tema', models.TextField()),
                ('Horario', models.TextField()),
                ('Comentario', models.TextField()),
                ('Asistencia', models.BooleanField(default=False)),
                ('Asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacion_Academica.asesoracademico')),
                ('Estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacion_Academica.estatusasesoria')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id_Personal', models.BigAutoField(primary_key=True, serialize=False)),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('Horario', models.TextField(default='lunes')),
                ('Huella', models.CharField(default='1', max_length=50)),
                ('Matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacion_Academica.alumno')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacion_Academica.rango')),
            ],
        ),
        migrations.CreateModel(
            name='AsesorPsicologico',
            fields=[
                ('id_Asesor', models.BigAutoField(primary_key=True, serialize=False)),
                ('Personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacion_Academica.personal')),
            ],
        ),
        migrations.AddField(
            model_name='asesoracademico',
            name='Personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacion_Academica.personal'),
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_Materia', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Carrera', models.ManyToManyField(to='Informacion_Academica.programaacademico')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='Carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacion_Academica.programaacademico'),
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id_Tema', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nombre', models.TextField()),
                ('Materias', models.ManyToManyField(to='Informacion_Academica.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_Ticket', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('Estatus', models.CharField(max_length=100)),
                ('asunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacion_Academica.tipo_insidencia')),
            ],
        ),
    ]
