# Generated by Django 5.0 on 2024-04-02 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informacion_Academica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesoriapsicologica',
            name='Asesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacion_Academica.asesorpsicologico'),
        ),
    ]
