# Generated by Django 5.0 on 2024-02-11 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informacion_Academica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id_Personal', models.BigAutoField(primary_key=True, serialize=False)),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('Matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacion_Academica.alumno')),
            ],
        ),
    ]
