# Generated by Django 5.0 on 2024-02-11 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informacion_Academica', '0002_personal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id_Rango', models.BigAutoField(primary_key=True, serialize=False)),
                ('Rango', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='personal',
            name='Usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='Rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Informacion_Academica.rango'),
            preserve_default=False,
        ),
    ]
