# Generated by Django 5.0 on 2024-02-28 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informacion_Academica', '0003_rango_personal_usuario_personal_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsesorAcademico',
            fields=[
                ('id_Asesor', models.BigAutoField(primary_key=True, serialize=False)),
                ('Horarios', models.TextField()),
                ('Materias', models.TextField()),
                ('Personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacion_Academica.personal')),
            ],
        ),
    ]
