# Generated by Django 5.0 on 2024-03-11 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informacion_Academica', '0004_asesoracademico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Insidencia',
            fields=[
                ('id_insidencia', models.BigAutoField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_Ticket', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('Estatus', models.CharField(max_length=100)),
                ('asunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacion_Academica.tipo_insidencia')),
            ],
        ),
    ]
