# Generated by Django 5.0 on 2024-04-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informacion_Academica', '0005_alter_asesoriapsicologica_asesor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_nota', models.BigAutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('Titulo', models.CharField(max_length=19)),
            ],
        ),
    ]
